---

- name: "PREREQ | PATCH | If required install libselinux package to manage file changes."
  ansible.builtin.package:
    name: python{{ ansible_facts['python']['version']['major'] }}{{ ansible_facts['python']['version']['minor'] }}-selinux
    state: present

- name: "PREREQ | PATCH | Ensure python3-rpm package is available"
  tags: always
  ansible.builtin.package:
    name: python{{ ansible_facts['python']['version']['major'] }}{{ ansible_facts['python']['version']['minor'] }}-rpm
    state: present

- name: "PREREQ | PATCH | Enable systemctl command procps is required"
  tags: always
  ansible.builtin.package:
    name: procps
    state: installed
