---

- name: "5.3.2.3.1 | PATCH | Ensure password history remember is configured"
  when:
    - suse16cis_rule_5_3_2_3_1
    - suse16cis_disruption_high
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_5.3.2.3.1
    - pam
    - NIST800-53R5_IA-5
  block:
    - name: "5.3.2.3.1 | AUDIT | Ensure password history remember is configured | Check existing files"
      when: suse16cis_use_pam_config
      ansible.builtin.command: pam-config --query --pwhistory --pwhistory-remember
      changed_when: false
      failed_when: discovered_pwhistory_remember.rc not in [ 0, 1 ]
      register: discovered_pwhistory_remember

    - name: "5.3.2.3.1 | PATCH | Ensure password history remember is configured | Ensure remember is set"
      when:
        - suse16cis_use_pam_config
        - discovered_pwhistory_remember.stdout is defined
        - "('remember=' + suse16cis_pamd_pwhistory_remember) not in discovered_pwhistory_remember.stdout"
      ansible.builtin.command: pam-config -a --pwhistory --pwhistory-remember={{ suse16cis_pamd_pwhistory_remember }}
      changed_when: true
      notify: Update pam-config

- name: "5.3.2.3.2 | PATCH | Ensure password history is enforced for the root user"
  when:
    - suse16cis_rule_5_3_2_3_2
    - suse16cis_disruption_high
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_5.3.2.3.2
    - pam
    - NIST800-53R5_IA-5
  block:
    - name: "5.3.2.3.2 | AUDIT | Ensure password history is enforced for the root user | Check existing files"
      when: suse16cis_use_pam_config
      ansible.builtin.command: pam-config --query --pwhistory
      changed_when: false
      failed_when: discovered_pwhistory_enforce_root.rc not in [ 0, 1 ]
      register: discovered_pwhistory_enforce_root

    - name: "5.3.2.3.2 | PATCH | Ensure password history is enforced for the root user | Ensure remember is set"
      when:
        - suse16cis_use_pam_config
        - discovered_pwhistory_enforce_root.stdout is defined
        - "'enforce_for_root' not in discovered_pwhistory_enforce_root.stdout"
      ansible.builtin.command: pam-config -a --pwhistory --pwhistory-enforce_for_root
      changed_when: true
      notify: Update pam-config

- name: "5.3.2.3.3 | PATCH | Ensure pam_pwhistory includes use_authtok"
  when:
    - suse16cis_rule_5_3_2_3_3
    - suse16cis_disruption_high
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_5.3.2.3.3
    - pam
    - NIST800-53R5_IA-5
  block:
    - name: "5.3.2.3.3 | AUDIT | Ensure pam_pwhistory includes use_authtok | Check existing files"
      ansible.builtin.shell: |
        set -o pipefail
        grep -P -- '^\s*password\s+([^#\n\r]+)\s+pam_pwhistory\.so\s+([^#\n\r]+\s+)?use_authtok\b' /etc/pam.d/*
      changed_when: false
      failed_when: discovered_pwhistory_use_authtok.rc not in [ 0, 1 ]
      args:
        executable: "{{ suse16cis_shell_executable }}"
      register: discovered_pwhistory_use_authtok

    - name: "5.3.2.3.3 | PATCH | Ensure pam_pwhistory includes use_authtok | pam-config"
      when:
        - suse16cis_use_pam_config
        - discovered_pwhistory_use_authtok.stdout | length == 0
      ansible.builtin.command: pam-config -a --pwhistory --pwhistory-use_authtok
      changed_when: true
      notify: Update pam-config

    - name: "5.3.2.3.3 | PATCH | Ensure pam_pwhistory includes use_authtok | Ensure authtok is set"
      when:
        - not suse16cis_use_pam_config
        - discovered_pwhistory_use_authtok.stdout | length == 0
      ansible.builtin.replace:
        path: /etc/pam.d/common-password
        regexp: '^(\s*password\s+\S+\s+pam_pwhistory\.so\s+(?!.*\buse_authtok\b).+)$'
        replace: '\1 use_authtok'
      changed_when: true
