---

- name: "6.2.3.1 | PATCH | Ensure modification of the /etc/sudoers file is collected"
  when: suse16cis_rule_6_2_3_1
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.1
    - NIST800-53R5_AU-12
  ansible.builtin.set_fact:
    update_audit_template: true

- name: "6.2.3.2 | PATCH | Ensure actions as another user are always logged"
  when: suse16cis_rule_6_2_3_2
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.2
    - NIST800-53R5_AC-6
  ansible.builtin.set_fact:
    update_audit_template: true

- name: "6.2.3.3 | PATCH | Ensure events that modify the sudo log file are collected"
  when: suse16cis_rule_6_2_3_3
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.3
  ansible.builtin.set_fact:
    update_audit_template: true

- name: "6.2.3.4 | PATCH | Ensure events that modify date and time information are collected"
  when: suse16cis_rule_6_2_3_4
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.4
    - NIST800-53R5_AU-3
    - NIST800-53R5_CM-6
  ansible.builtin.set_fact:
    update_audit_template: true

- name: "6.2.3.5 | PATCH | Ensure events that modify sethostname and setdomainname are collected"
  when: suse16cis_rule_6_2_3_5
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.5
    - NIST800-53R5_AU-3
    - NIST800-53R5_CM-6
  ansible.builtin.set_fact:
    update_audit_template: true

- name: "6.2.3.6 | PATCH | Ensure events that modify /etc/issue and /etc/issue.net are collected"
  when: suse16cis_rule_6_2_3_6
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.6
    - NIST800-53R5_AU-3
    - NIST800-53R5_CM-6
  ansible.builtin.set_fact:
    update_audit_template: true

- name: "6.2.3.7 | PATCH | Ensure events that modify /etc/hosts and /etc/hostname are collected"
  when: suse16cis_rule_6_2_3_7
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.7
    - NIST800-53R5_AU-3
    - NIST800-53R5_CM-6
  ansible.builtin.set_fact:
    update_audit_template: true

- name: "6.2.3.8 | PATCH | Ensure events that modify /etc/NetworkManager directory are collected"
  when: suse16cis_rule_6_2_3_8
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.8
    - NIST800-53R5_AU-2
    - NIST800-53R5_AU-12
  ansible.builtin.set_fact:
    update_audit_template: true

- name: "6.2.3.9 | PATCH | Ensure use of privileged commands are collected"
  when: suse16cis_rule_6_2_3_9
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.9
    - NIST800-53R5_AU-9
    - NIST800-53R5_AU-12
  block:
    - name: "6.2.3.9 | PATCH | Ensure use of privileged commands are collected | discover privileged procs"
      ansible.builtin.shell: |
        set -o pipefail
        find / -xdev -perm /6000 -type f 2>/dev/null | sort
      args:
        executable: "{{ suse16cis_shell_executable }}"
      changed_when: false
      failed_when: false
      check_mode: false
      register: discovered_priv_procs

    - name: "6.2.3.9 | PATCH | Ensure use of privileged commands are collected | set audit template"
      ansible.builtin.set_fact:
        update_audit_template: true
      notify: update auditd

- name: "6.2.3.10 | PATCH | Ensure unsuccessful file access attempts are collected"
  when: suse16cis_rule_6_2_3_10
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.10
    - NIST800-53R5_AU-9
    - NIST800-53R5_AU-12
  ansible.builtin.set_fact:
    update_audit_template: true

- name: "6.2.3.11 | PATCH | Ensure events that modify /etc/group information are collected"
  when: suse16cis_rule_6_2_3_11
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.11
    - NIST800-53R5_AU-9
    - NIST800-53R5_AU-12
  ansible.builtin.set_fact:
    update_audit_template: true

- name: "6.2.3.12 | PATCH | Ensure events that modify /etc/passwd information are collected"
  when: suse16cis_rule_6_2_3_12
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.12
    - NIST800-53R5_AU-9
    - NIST800-53R5_AU-12
  ansible.builtin.set_fact:
    update_audit_template: true

- name: "6.2.3.13 | PATCH | Ensure events that modify /etc/shadow and /etc/gshadow are collected"
  when: suse16cis_rule_6_2_3_13
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.13
    - NIST800-53R5_AU-9
    - NIST800-53R5_AU-12
  ansible.builtin.set_fact:
    update_audit_template: true

- name: "6.2.3.14 | PATCH | Ensure events that modify /etc/security/opasswd are collected"
  when: suse16cis_rule_6_2_3_14
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.14
    - NIST800-53R5_AU-9
    - NIST800-53R5_AU-12
  ansible.builtin.set_fact:
    update_audit_template: true

- name: "6.2.3.15 | PATCH | Ensure events that modify /etc/pam.d/ information are collected"
  when: suse16cis_rule_6_2_3_15
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.15
    - NIST800-53R5_AU-9
    - NIST800-53R5_AU-12
  ansible.builtin.set_fact:
    update_audit_template: true

- name: "6.2.3.16 | PATCH | Ensure discretionary access control permission modification events chmod,fchmod,fchmodat,fchmodat2 are collected"
  when: suse16cis_rule_6_2_3_16
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.16
    - NIST800-53R5_AU-9
    - NIST800-53R5_AU-12
  ansible.builtin.set_fact:
    update_audit_template: true

- name: "6.2.3.17 | PATCH | Ensure discretionary access control permission modification events chown,fchown,lchown,fchownat are collected"
  when: suse16cis_rule_6_2_3_17
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.17
    - NIST800-53R5_AU-9
    - NIST800-53R5_AU-12
  ansible.builtin.set_fact:
    update_audit_template: true

- name: "6.2.3.18 | PATCH | Ensure discretionary access control permission modification events setxattr,lsetxattr,fsetxattr,removexattr,lremovexattr,fremovexattr collected"
  when: suse16cis_rule_6_2_3_18
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.18
    - NIST800-53R5_AU-9
    - NIST800-53R5_AU-12
  ansible.builtin.set_fact:
    update_audit_template: true

- name: "6.2.3.19 | PATCH | Ensure successful file system mounts are collected"
  when: suse16cis_rule_6_2_3_19
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.19
    - NIST800-53R5_AU-12
    - NIST800-53R5_CM-6
  ansible.builtin.set_fact:
    update_audit_template: true

- name: "6.2.3.20 | PATCH | Ensure session initiation information is collected"
  when: suse16cis_rule_6_2_3_20
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.20
    - NIST800-53R5_AU-12
  ansible.builtin.set_fact:
    update_audit_template: true

- name: "6.2.3.21 | PATCH | Ensure login and logout events are collected"
  when: suse16cis_rule_6_2_3_21
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.21
    - NIST800-53R5_AU-12
  ansible.builtin.set_fact:
    update_audit_template: true

- name: "6.2.3.22 | PATCH | Ensure unlink file deletion events by users are collected"
  when: suse16cis_rule_6_2_3_22
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.22
    - NIST800-53R5_AU-12
  ansible.builtin.set_fact:
    update_audit_template: true

- name: "6.2.3.23 | PATCH | Ensure rename file deletion events by users are collected"
  when: suse16cis_rule_6_2_3_23
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.23
    - NIST800-53R5_AU-12
  ansible.builtin.set_fact:
    update_audit_template: true

- name: "6.2.3.24 | PATCH | Ensure events that modify the system's Mandatory Access Controls are collected"
  when: suse16cis_rule_6_2_3_24
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.24
    - NIST800-53R5_AU-12
    - NIST800-53R5_CM-6
  ansible.builtin.set_fact:
    update_audit_template: true

- name: "6.2.3.25 | PATCH | Ensure successful and unsuccessful attempts to use the chcon command are collected"
  when: suse16cis_rule_6_2_3_25
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.25
    - NIST800-53R5_AU-9
    - NIST800-53R5_AU-12
  ansible.builtin.set_fact:
    update_audit_template: true

- name: "6.2.3.26 | PATCH | Ensure successful and unsuccessful attempts to use the setfacl command are collected"
  when: suse16cis_rule_6_2_3_26
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.26
    - NIST800-53R5_AU-9
    - NIST800-53R5_AU-12
  ansible.builtin.set_fact:
    update_audit_template: true

- name: "6.2.3.27 | PATCH | Ensure successful and unsuccessful attempts to use the chacl command are collected"
  when: suse16cis_rule_6_2_3_27
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.27
    - NIST800-53R5_AU-9
    - NIST800-53R5_AU-12
  ansible.builtin.set_fact:
    update_audit_template: true

- name: "6.2.3.28 | PATCH | Ensure successful and unsuccessful attempts to use the usermod command are collected"
  when: suse16cis_rule_6_2_3_28
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.28
    - NIST800-53R5_AU-9
    - NIST800-53R5_AU-12
  ansible.builtin.set_fact:
    update_audit_template: true

- name: "6.2.3.29 | PATCH | Ensure kernel module loading unloading and modification is collected"
  when: suse16cis_rule_6_2_3_29
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.29
    - NIST800-53R5_AU-12
    - NIST800-53R5_CM-7
  ansible.builtin.set_fact:
    update_audit_template: true

- name: '6.2.3.30 | PATCH | Ensure kernel "init_module" and "finit_module" loading unloading and modification is collected'
  when: suse16cis_rule_6_2_3_30
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.30
    - NIST800-53R5_AU-12
    - NIST800-53R5_CM-7
  ansible.builtin.set_fact:
    update_audit_template: true

- name: '6.2.3.31 | PATCH | Ensure kernel "delete_module" loading unloading and modification is collected'
  when: suse16cis_rule_6_2_3_31
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.31
    - NIST800-53R5_AU-12
    - NIST800-53R5_CM-7
  ansible.builtin.set_fact:
    update_audit_template: true

- name: '6.2.3.32 | PATCH | Ensure kernel "create_module" and "query_module" loading unloading and modification is collected'
  when: suse16cis_rule_6_2_3_32
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.32
    - NIST800-53R5_AU-12
    - NIST800-53R5_CM-7
  ansible.builtin.set_fact:
    update_audit_template: true

- name: "6.2.3.33 | PATCH | Ensure the audit configuration is loaded regardless of errors"
  when: suse16cis_rule_6_2_3_33
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.33
    - NIST800-53R5_AU-12
  ansible.builtin.set_fact:
    update_audit_template: true

- name: "6.2.3.34 | PATCH | Ensure the audit configuration is immutable"
  when: suse16cis_rule_6_2_3_34
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - rule_6.2.3.34
    - NIST800-53R5_AU-9
  ansible.builtin.set_fact:
    update_audit_template: true

- name: "6.2.3.35 | AUDIT | Ensure the running and on disk configuration is the same"
  when: suse16cis_rule_6_2_3_35
  tags:
    - level2-server
    - level2-workstation
    - manual
    - auditd
    - audit
    - rule_6.2.3.35
    - NIST800-53R5_AU-12
  ansible.builtin.debug:
    msg: "6.2.3.35 runs after the template updates have been carried out and will warn if errors and reboot not required"
