---

- name: "1.2.1.1 | AUDIT | Ensure GPG keys are configured"
  when: suse16cis_rule_1_2_1_1
  tags:
    - level1-server
    - level1-workstation
    - manual
    - patch
    - rule_1.2.1.1
    - NIST800-53R5_SI-2
  block:
    - name: "1.2.1.1 | AUDIT | Ensure GPG keys are configured | list installed pubkey keys"
      ansible.builtin.shell: |
        set -o pipefail
        rpm -qa | grep "{{ os_gpg_key_pubkey_name }}"
      changed_when: false
      failed_when: false
      args:
        executable: "{{ suse16cis_shell_executable }}"
      register: discovered_os_installed_pub_keys

    - name: "1.2.1.1 | AUDIT | Ensure GPG keys are configured | Query found keys"
      when: discovered_os_installed_pub_keys.rc == 0
      ansible.builtin.shell: |
        set -o pipefail
        rpm -q --queryformat "%{PACKAGER} %{VERSION}\n" {{ os_gpg_key_pubkey_name }} | grep "{{ os_gpg_key_pubkey_content }}"
      changed_when: false
      failed_when: false
      args:
        executable: "{{ suse16cis_shell_executable }}"
      register: discovered_os_gpg_key_check

    - name: "1.2.1.1 | AUDIT | Ensure GPG keys are configured | expected keys fail"
      when:
        - discovered_os_installed_pub_keys.rc == 1 or
          discovered_os_gpg_key_check.rc == 1
      ansible.builtin.fail:
        msg: Installed GPG Keys do not meet expected values or expected keys are not installed

- name: "1.2.1.2/3 | AUDIT | Find repos file"
  when: suse16cis_rule_1_2_1_2 or suse16cis_rule_1_2_1_3
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_1.2.1.2
    - rule_1.2.1.3
    - NIST800-53R5_SI-2
  ansible.builtin.find:
    paths: /etc/zypp/repos.d
    patterns: "*.repo"
  register: discovered_repofiles

- name: "1.2.1.2 | PATCH | Ensure gpgcheck is configured"
  when: suse16cis_rule_1_2_1_2
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_1.2.1.2
    - NIST800-53R5_SI-2
  ansible.builtin.replace:
    name: "{{ item.path }}"
    regexp: ^gpgcheck\s*=\s*(0|false|no|off)
    replace: "gpgcheck=on"
  loop: "{{ discovered_repofiles.files }}"
  loop_control:
    label: "{{ item.path }}"

- name: "1.2.1.3 | AUDIT | Ensure repo_gpgcheck is configured"
  when: suse16cis_rule_1_2_1_3
  tags:
    - level2-server
    - level2-workstation
    - patch
    - rule_1.2.1.3
    - NIST800-53R5_SI-2
  block:
    - name: "1.2.1.3 | PATCH | Ensure repo_gpgcheck is configured | zypp.conf.d"
      community.general.ini_file:
        path: /etc/zypp/zypp.conf.d/repogpg_check.conf
        section: main
        option: repo_gpgcheck
        value: "1"
        no_extra_spaces: true
        create: true
        owner: root
        group: root
        mode: 'u-x,g-wx,o-rwx'

    - name: "1.2.1.3 | PATCH | Ensure repo_gpgcheck is configured | amend repo files"
      ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: ^repo_gpgcheck\s*=\s*(0|false|no|off)
        replace: repo_gpgcheck=on
      loop: "{{ discovered_repofiles.files }}"
      loop_control:
        label: "{{ item.path }}"

- name: "1.2.1.4 | AUDIT | Ensure package manager repositories are configured"
  when: suse16cis_rule_1_2_1_4
  tags:
    - level1-server
    - level1-workstation
    - audit
    - rule_1.2.1.4
    - NIST800-53R5_SI-2
  block:
    - name: "1.2.1.4 | AUDIT | Ensure package manager repositories are configured | Get repo list"
      ansible.builtin.command: zypper lr
      changed_when: false
      failed_when: false
      check_mode: false
      register: discovered_repolist

    - name: "1.2.1.4 | AUDIT | Ensure package manager repositories are configured | Display repo list"
      ansible.builtin.debug:
        msg:
          - "Warning!! Below are the configured repos. Please review and make sure all align with site policy"
          - "{{ discovered_repolist.stdout_lines }}"

    - name: "1.2.1.4 | AUDIT | Ensure package manager repositories are configured | Warn Count"
      ansible.builtin.import_tasks:
        file: warning_facts.yml
      vars:
        warn_control_id: '1.2.1.4'

- name: "1.2.1.5 | PATCH | Ensure weak dependencies are configured"
  when: suse16cis_rule_1_2_1_5
  tags:
    - level2-server
    - level2-workstation
    - patch
    - rule_1.2.1.5
    - NIST800-53R5_CM-7
  community.general.ini_file:
    path: /etc/zypp/zypp.conf
    section: main
    option: solver.onlyRequires
    value: "true"
    create: true
    owner: root
    group: root
    mode: 'u-x,g-wx,o-rwx'
